In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('data/loan-train.csv')
df.T

0         1         2             3         4    \
Loan_ID            LP001002  LP001003  LP001005      LP001006  LP001008   
Gender                 Male      Male      Male          Male      Male   
Married                  No       Yes       Yes           Yes        No   
Dependents                0         1         0             0         0   
Education          Graduate  Graduate  Graduate  Not Graduate  Graduate   
Self_Employed            No        No       Yes            No        No   
ApplicantIncome        5849      4583      3000          2583      6000   
CoapplicantIncome       0.0    1508.0       0.0        2358.0       0.0   
LoanAmount              NaN     128.0      66.0         120.0     141.0   
Loan_Amount_Term      360.0     360.0     360.0         360.0     360.0   
Credit_History          1.0       1.0       1.0           1.0       1.0   
Property_Area         Urban     Rural     Urban         Urban     Urban   
Loan_Status               Y         N         Y             Y         Y   

                        5             6          7         8          9    \
Loan_ID            LP001011      LP001013   LP001014  LP001018   LP001020   
Gender                 Male          Male       Male      Male       Male   
Married                 Yes           Yes        Yes       Yes        Yes   
Dependents                2             0         3+         2          1   
Education          Graduate  Not Graduate   Graduate  Graduate   Graduate   
Self_Employed           Yes            No         No        No         No   
ApplicantIncome        5417          2333       3036      4006      12841   
CoapplicantIncome    4196.0        1516.0     2504.0    1526.0    10968.0   
LoanAmount            267.0          95.0      158.0     168.0      349.0   
Loan_Amount_Term      360.0         360.0      360.0     360.0      360.0   
Credit_History          1.0           1.0        0.0       1.0        1.0   
Property_Area         Urban         Urban  Semiurban     Urban  Semiurban   
Loan_Status               Y             Y          N         Y          N   

                   ...        604           605        606           607  \
Loan_ID            ...   LP002959      LP002960   LP002961      LP002964   
Gender             ...     Female          Male       Male          Male   
Married            ...        Yes           Yes        Yes           Yes   
Dependents         ...          1             0          1             2   
Education          ...   Graduate  Not Graduate   Graduate  Not Graduate   
Self_Employed      ...         No            No         No            No   
ApplicantIncome    ...      12000          2400       3400          3987   
CoapplicantIncome  ...        0.0        3800.0     2500.0        1411.0   
LoanAmount         ...      496.0           NaN      173.0         157.0   
Loan_Amount_Term   ...      360.0         180.0      360.0         360.0   
Credit_History     ...        1.0           1.0        1.0           1.0   
Property_Area      ...  Semiurban         Urban  Semiurban         Rural   
Loan_Status        ...          Y             N          Y             Y   

                        608       609       610       611       612        613  
Loan_ID            LP002974  LP002978  LP002979  LP002983  LP002984   LP002990  
Gender                 Male    Female      Male      Male      Male     Female  
Married                 Yes        No       Yes       Yes       Yes         No  
Dependents                0         0        3+         1         2          0  
Education          Graduate  Graduate  Graduate  Graduate  Graduate   Graduate  
Self_Employed            No        No        No        No        No        Yes  
ApplicantIncome        3232      2900      4106      8072      7583       4583  
CoapplicantIncome    1950.0       0.0       0.0     240.0       0.0        0.0  
LoanAmount            108.0      71.0      40.0     253.0     187.0      133.0  
Loan_Amount_Term   

In [4]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [12]:
df[df['Gender'].isnull()]

Loan_ID Gender Married Dependents     Education Self_Employed  \
23   LP001050    NaN     Yes          2  Not Graduate            No   
126  LP001448    NaN     Yes         3+      Graduate            No   
171  LP001585    NaN     Yes         3+      Graduate            No   
188  LP001644    NaN     Yes          0      Graduate           Yes   
314  LP002024    NaN     Yes          0      Graduate            No   
334  LP002103    NaN     Yes          1      Graduate           Yes   
460  LP002478    NaN     Yes          0      Graduate           Yes   
467  LP002501    NaN     Yes          0      Graduate            No   
477  LP002530    NaN     Yes          2      Graduate            No   
507  LP002625    NaN      No          0      Graduate            No   
576  LP002872    NaN     Yes          0      Graduate            No   
588  LP002925    NaN      No          0      Graduate            No   
592  LP002933    NaN      No         3+      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
23              3365             1917.0       112.0             360.0   
126            23803                0.0       370.0             360.0   
171            51763                0.0       700.0             300.0   
188              674             5296.0       168.0             360.0   
314             2473             1843.0       159.0             360.0   
334             9833             1833.0       182.0             180.0   
460             2083             4083.0       160.0             360.0   
467            16692                0.0       110.0             360.0   
477             2873             1872.0       132.0             360.0   
507             3583                0.0        96.0             360.0   
576             3087             2210.0       136.0             360.0   
588             4750                0.0        94.0             360.0   
592             9357                0.0       292.0             360.0   

     Credit_History Property_Area Loan_Status  
23              0.0         Rural           N  
126             1.0         Rural           Y  
171             1.0         Urban           Y  
188             1.0         Rural           Y  
314             1.0         Rural           N  
334             1.0         Urban           Y  
460             NaN     Semiurban           Y  
467             1.0     Semiurban           Y  
477             0.0     Semiurban           N  
507             1.0         Urban           N  
576             0.0     Semiurban           N  
588             1.0     Semiurban           Y  
592             1.0     Semiurban           Y

In [58]:
import numpy as np
df['Gender'] == np.nan

0      False
1      False
2      False
3      False
4      False
       ...  
609    False
610    False
611    False
612    False
613    False
Name: Gender, Length: 614, dtype: bool

In [18]:
df['Gender']= df['Gender'].fillna('Male')
np.unique(df['Gender'])

array(['Female', 'Male'], dtype=object)

In [19]:
print(df['Married'].unique())

['No' 'Yes' nan]


In [20]:
df['Married'] = df['Married'].fillna('Yes')
df['Married'].unique()

array(['No', 'Yes'], dtype=object)

In [64]:
import numpy as np
df['Dependents'] == np.nan

0      False
1      False
2      False
3      False
4      False
       ...  
609    False
610    False
611    False
612    False
613    False
Name: Dependents, Length: 614, dtype: bool

In [69]:
df['Dependents'] = df['Dependents'].fillna('0')
df = df.replace(to_replace = '3+', value='3')
df['Dependents'].unique()

array(['0', '1', '2', '3'], dtype=object)

In [72]:
df['Self_Employed'] = df['Self_Employed'].fillna(method='pad')
df['Self_Employed'].unique()

C:\Users\user\AppData\Local\Temp\ipykernel_21912\3459211411.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Self_Employed'] = df['Self_Employed'].fillna(method='pad')


array(['No', 'Yes'], dtype=object)

In [73]:
df['LoanAmount'] = df['LoanAmount'].fillna(method='bfill')
df['LoanAmount'].unique()

C:\Users\user\AppData\Local\Temp\ipykernel_21912\1281842164.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['LoanAmount'] = df['LoanAmount'].fillna(method='bfill')


array([128.,  66., 120., 141., 267.,  95., 158., 168., 349.,  70., 109.,
       200., 114.,  17., 125., 100.,  76., 133., 115., 104., 315., 116.,
       112., 151., 191., 122., 110.,  35., 201.,  74., 106., 320., 144.,
       184.,  80.,  47.,  75., 134.,  96.,  88.,  44., 286.,  97., 135.,
       180.,  99., 165., 258., 126., 312., 136., 172.,  81., 187., 113.,
       176., 130., 111., 167., 265.,  50., 210., 175., 131., 188.,  25.,
       137., 160., 225., 216.,  94., 139., 152., 118., 185., 154.,  85.,
       259., 194.,  93., 370., 182., 650., 102., 290.,  84., 242., 129.,
        30., 244., 600., 255.,  98., 275., 121.,  63., 700.,  87., 101.,
       495.,  67.,  73., 260., 108.,  58.,  48., 164., 170.,  83.,  90.,
       166., 124.,  55.,  59., 127., 214., 240.,  72.,  60., 138.,  42.,
       280., 140., 155., 123., 279., 192., 304., 330., 150., 207., 436.,
        78.,  54.,  89., 143., 105., 132., 480.,  56., 159., 300., 376.,
       117.,  71., 490., 173.,  46., 228., 308., 23

In [76]:
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median())
df['Loan_Amount_Term'].unique()

array([360., 120., 240., 180.,  60., 300., 480.,  36.,  84.,  12.])

In [77]:
df['Credit_History'].unique()

array([ 1.,  0., nan])

In [81]:
df['Credit_History'] = df['Credit_History'].fillna(1.0)
df['Credit_History'].unique()

array([1.0, 0.0, '1.0'], dtype=object)

In [91]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [84]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History        object
Property_Area         object
Loan_Status           object
dtype: object

In [85]:
df['Dependents'] = pd.to_numeric(df['Dependents'])

In [86]:
df.T

0         1         2             3         4    \
Loan_ID            LP001002  LP001003  LP001005      LP001006  LP001008   
Gender                 Male      Male      Male          Male      Male   
Married                  No       Yes       Yes           Yes        No   
Dependents                0         1         0             0         0   
Education          Graduate  Graduate  Graduate  Not Graduate  Graduate   
Self_Employed            No        No       Yes            No        No   
ApplicantIncome        5849      4583      3000          2583      6000   
CoapplicantIncome       0.0    1508.0       0.0        2358.0       0.0   
LoanAmount            128.0     128.0      66.0         120.0     141.0   
Loan_Amount_Term      360.0     360.0     360.0         360.0     360.0   
Credit_History          1.0       1.0       1.0           1.0       1.0   
Property_Area         Urban     Rural     Urban         Urban     Urban   
Loan_Status               Y         N         Y             Y         Y   

                        5             6          7         8          9    \
Loan_ID            LP001011      LP001013   LP001014  LP001018   LP001020   
Gender                 Male          Male       Male      Male       Male   
Married                 Yes           Yes        Yes       Yes        Yes   
Dependents                2             0          3         2          1   
Education          Graduate  Not Graduate   Graduate  Graduate   Graduate   
Self_Employed           Yes            No         No        No         No   
ApplicantIncome        5417          2333       3036      4006      12841   
CoapplicantIncome    4196.0        1516.0     2504.0    1526.0    10968.0   
LoanAmount            267.0          95.0      158.0     168.0      349.0   
Loan_Amount_Term      360.0         360.0      360.0     360.0      360.0   
Credit_History          1.0           1.0        0.0       1.0        1.0   
Property_Area         Urban         Urban  Semiurban     Urban  Semiurban   
Loan_Status               Y             Y          N         Y          N   

                   ...        604           605        606           607  \
Loan_ID            ...   LP002959      LP002960   LP002961      LP002964   
Gender             ...     Female          Male       Male          Male   
Married            ...        Yes           Yes        Yes           Yes   
Dependents         ...          1             0          1             2   
Education          ...   Graduate  Not Graduate   Graduate  Not Graduate   
Self_Employed      ...         No            No         No            No   
ApplicantIncome    ...      12000          2400       3400          3987   
CoapplicantIncome  ...        0.0        3800.0     2500.0        1411.0   
LoanAmount         ...      496.0         173.0      173.0         157.0   
Loan_Amount_Term   ...      360.0         180.0      360.0         360.0   
Credit_History     ...        1.0           1.0        1.0           1.0   
Property_Area      ...  Semiurban         Urban  Semiurban         Rural   
Loan_Status        ...          Y             N          Y             Y   

                        608       609       610       611       612        613  
Loan_ID            LP002974  LP002978  LP002979  LP002983  LP002984   LP002990  
Gender                 Male    Female      Male      Male      Male     Female  
Married                 Yes        No       Yes       Yes       Yes         No  
Dependents                0         0         3         1         2          0  
Education          Graduate  Graduate  Graduate  Graduate  Graduate   Graduate  
Self_Employed            No        No        No        No        No        Yes  
ApplicantIncome        3232      2900      4106      8072      7583       4583  
CoapplicantIncome    1950.0       0.0       0.0     240.0       0.0        0.0  
LoanAmount            108.0      71.0      40.0     253.0     187.0      133.0  
Loan_Amount_Term   

In [88]:
df['Credit_History'] = pd.to_numeric(df['Credit_History'])

In [89]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents             int64
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [95]:
df.describe()

Gender  Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
count     0.0  614.000000       614.000000         614.000000  614.000000   
mean      NaN    0.744300      5403.459283        1621.245798  146.416938   
std       NaN    1.009623      6109.041673        2926.248369   84.917398   
min       NaN    0.000000       150.000000           0.000000    9.000000   
25%       NaN    0.000000      2877.500000           0.000000  100.000000   
50%       NaN    0.000000      3812.500000        1188.500000  128.000000   
75%       NaN    1.000000      5795.000000        2297.250000  166.750000   
max       NaN    3.000000     81000.000000       41667.000000  700.000000   

       Loan_Amount_Term  Credit_History  
count        614.000000      614.000000  
mean         342.410423        0.855049  
std           64.428629        0.352339  
min           12.000000        0.000000  
25%          360.000000        1.000000  
50%          360.000000        1.000000  
75%          360.000000        1.000000  
max          480.000000        1.000000